version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
      - cd Newlambda
      - pip install -r requirements.txt -t  lib
  build:
    commands:
      - cd ..
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function1.py
      - cd Newlambda
      - cd lib
      - zip -r9 ../deployment_package1.zip .
      - cd ..
      - zip -g deployment_package1.zip lambda_function.py
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - cd ..
      - aws lambda update-function-code --function-name lambdaCICD --zip-file fileb://deployment_package.zip
      - cd Newlambda
      - aws lambda update-function-code --function-name lambdaCICD1 --zip-file fileb://deployment_package1.zip
      - echo "DONE update"
      # - aws lambda list-functions